name = "Example workflow"

[steps.s1]
name = "Step 1"
commands = ["sleep 1"]

[steps.s2]
name = "Step 2"
commands = ["sleep 1"]
needs = ["s1"]

[steps.s3]
name = "Step 3"
commands = ["echo hello"]
needs = ["s2"]
