name: Test CLI Module

on:
  push:
    paths: ["cli/**", "types/**"]
  pull_request:
    paths: ["cli/**", "types/**"]
  workflow_call:
  workflow_dispatch: 

jobs:
  test:
    uses: './.github/workflows/test.yml'
    with:
      working-directory: cli
