name: Test Bun Module
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      test-command:
        required: false
        type: string
        default: bun run test
      lint-command:
        required: false
        type: string
        default: bun run lint

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: bun install

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Lint
        if: ${{ inputs.lint-command != '' }}
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.lint-command }}
